kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31000
    hostPort: 8443
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32000
    hostPort: 15021
    listenAddress: "127.0.0.1"
    protocol: TCP